
exports.run = (client, message) => {
    message.delete({timeout: 0})

    var randlet, randlet3;
            function random(min, max){
                min = Math.ceil(0);
                max = Math.floor(25);
                
                randlet = Math.floor(Math.random() * (max - min +1)+ min);
                randlet2 = Math.floor(Math.random() * (max - min +1)+ min);
                randlet3 = Math.floor(Math.random() * (max - min +1)+ min);
                randlet4 = Math.floor(Math.random() * (max - min +1)+ min);
                randlet5 = Math.floor(Math.random() * (max - min +1)+ min);
                randlet6 = Math.floor(Math.random() * (max - min +1)+ min);
                randlet7 = Math.floor(Math.random() * (max - min +1)+ min);
                randlet8 = Math.floor(Math.random() * (max - min +1)+ min);
                randlet9 = Math.floor(Math.random() * (max - min +1)+ min);

                if(randlet == '0') { randlet = 'A'; }
                if(randlet == '1') { randlet = 'B'; }
                if(randlet == '2') { randlet = 'C'; }
                if(randlet == '3') { randlet = 'D'; }
                if(randlet == '4') { randlet = 'E'; }
                if(randlet == '5') { randlet = 'F'; }
                if(randlet == '6') { randlet = 'G'; }
                if(randlet == '7') { randlet = 'H'; }
                if(randlet == '8') { randlet = 'I'; }
                if(randlet == '9') { randlet = 'J'; }
                if(randlet == '10') { randlet = 'K'; }
                if(randlet == '11') { randlet = 'L'; }
                if(randlet == '12') { randlet = 'M'; }
                if(randlet == '13') { randlet = 'N'; }
                if(randlet == '14') { randlet = 'O'; }
                if(randlet == '15') { randlet = 'P'; }
                if(randlet == '16') { randlet = 'Q'; }
                if(randlet == '17') { randlet = 'R'; }
                if(randlet == '18') { randlet = 'S'; }
                if(randlet == '19') { randlet = 'T'; }
                if(randlet == '20') { randlet = 'U'; }
                if(randlet == '21') { randlet = 'V'; }
                if(randlet == '22') { randlet = 'W'; }
                if(randlet == '23') { randlet = 'X'; }
                if(randlet == '24') { randlet = 'Y'; }
                if(randlet == '25') { randlet = 'Z'; }
                if(randlet2 == '0') { randlet2 = 'A'; }
                if(randlet2 == '1') { randlet2 = 'B'; }
                if(randlet2 == '2') { randlet2 = 'C'; }
                if(randlet2 == '3') { randlet2 = 'D'; }
                if(randlet2 == '4') { randlet2 = 'E'; }
                if(randlet2 == '5') { randlet2 = 'F'; }
                if(randlet2 == '6') { randlet2 = 'G'; }
                if(randlet2 == '7') { randlet2 = 'H'; }
                if(randlet2 == '8') { randlet2 = 'I'; }
                if(randlet2 == '9') { randlet2 = 'J'; }
                if(randlet2 == '10') { randlet2 = 'K'; }
                if(randlet2 == '11') { randlet2 = 'L'; }
                if(randlet2 == '12') { randlet2 = 'M'; }
                if(randlet2 == '13') { randlet2 = 'N'; }
                if(randlet2 == '14') { randlet2 = 'O'; }
                if(randlet2 == '15') { randlet2 = 'P'; }
                if(randlet2 == '16') { randlet2 = 'Q'; }
                if(randlet2 == '17') { randlet2 = 'R'; }
                if(randlet2 == '18') { randlet2 = 'S'; }
                if(randlet2 == '19') { randlet2 = 'T'; }
                if(randlet2 == '20') { randlet2 = 'U'; }
                if(randlet2 == '21') { randlet2 = 'V'; }
                if(randlet2 == '22') { randlet2 = 'W'; }
                if(randlet2 == '23') { randlet2 = 'X'; }
                if(randlet2 == '24') { randlet2 = 'Y'; }
                if(randlet2 == '25') { randlet2 = 'Z'; }
                if(randlet3 == '0') { randlet3 = 'A'; }
                if(randlet3 == '1') { randlet3 = 'B'; }
                if(randlet3 == '2') { randlet3 = 'C'; }
                if(randlet3 == '3') { randlet3 = 'D'; }
                if(randlet3 == '4') { randlet3 = 'E'; }
                if(randlet3 == '5') { randlet3 = 'F'; }
                if(randlet3 == '6') { randlet3 = 'G'; }
                if(randlet3 == '7') { randlet3 = 'H'; }
                if(randlet3 == '8') { randlet3 = 'I'; }
                if(randlet3 == '9') { randlet3 = 'J'; }
                if(randlet3 == '10') { randlet3 = 'K'; }
                if(randlet3 == '11') { randlet3 = 'L'; }
                if(randlet3 == '12') { randlet3 = 'M'; }
                if(randlet3 == '13') { randlet3 = 'N'; }
                if(randlet3 == '14') { randlet3 = 'O'; }
                if(randlet3 == '15') { randlet3 = 'P'; }
                if(randlet3 == '16') { randlet3 = 'Q'; }
                if(randlet3 == '17') { randlet3 = 'R'; }
                if(randlet3 == '18') { randlet3 = 'S'; }
                if(randlet3 == '19') { randlet3 = 'T'; }
                if(randlet3 == '20') { randlet3 = 'U'; }
                if(randlet3 == '21') { randlet3 = 'V'; }
                if(randlet3 == '22') { randlet3 = 'W'; }
                if(randlet3 == '23') { randlet3 = 'X'; }
                if(randlet3 == '24') { randlet3 = 'Y'; }
                if(randlet3 == '25') { randlet3 = 'Z'; }
                if(randlet4 == '0') { randlet4 = 'A'; }
                if(randlet4 == '1') { randlet4 = 'B'; }
                if(randlet4 == '2') { randlet4 = 'C'; }
                if(randlet4 == '3') { randlet4 = 'D'; }
                if(randlet4 == '4') { randlet4 = 'E'; }
                if(randlet4 == '5') { randlet4 = 'F'; }
                if(randlet4 == '6') { randlet4 = 'G'; }
                if(randlet4 == '7') { randlet4 = 'H'; }
                if(randlet4 == '8') { randlet4 = 'I'; }
                if(randlet4 == '9') { randlet4 = 'J'; }
                if(randlet4 == '10') { randlet4 = 'K'; }
                if(randlet4 == '11') { randlet4 = 'L'; }
                if(randlet4 == '12') { randlet4 = 'M'; }
                if(randlet4 == '13') { randlet4 = 'N'; }
                if(randlet4 == '14') { randlet4 = 'O'; }
                if(randlet4 == '15') { randlet4 = 'P'; }
                if(randlet4 == '16') { randlet4 = 'Q'; }
                if(randlet4 == '17') { randlet4 = 'R'; }
                if(randlet4 == '18') { randlet4 = 'S'; }
                if(randlet4 == '19') { randlet4 = 'T'; }
                if(randlet4 == '20') { randlet4 = 'U'; }
                if(randlet4 == '21') { randlet4 = 'V'; }
                if(randlet4 == '22') { randlet4 = 'W'; }
                if(randlet4 == '23') { randlet4 = 'X'; }
                if(randlet4 == '24') { randlet4 = 'Y'; }
                if(randlet4 == '25') { randlet4 = 'Z'; }
                if(randlet5 == '0') { randlet5 = 'A'; }
                if(randlet5 == '1') { randlet5 = 'B'; }
                if(randlet5 == '2') { randlet5 = 'C'; }
                if(randlet5 == '3') { randlet5 = 'D'; }
                if(randlet5 == '4') { randlet5 = 'E'; }
                if(randlet5 == '5') { randlet5 = 'F'; }
                if(randlet5 == '6') { randlet5 = 'G'; }
                if(randlet5 == '7') { randlet5 = 'H'; }
                if(randlet5 == '8') { randlet5 = 'I'; }
                if(randlet5 == '9') { randlet5 = 'J'; }
                if(randlet5 == '10') { randlet5 = 'K'; }
                if(randlet5 == '11') { randlet5 = 'L'; }
                if(randlet5 == '12') { randlet5 = 'M'; }
                if(randlet5 == '13') { randlet5 = 'N'; }
                if(randlet5 == '14') { randlet5 = 'O'; }
                if(randlet5 == '15') { randlet5 = 'P'; }
                if(randlet5 == '16') { randlet5 = 'Q'; }
                if(randlet5 == '17') { randlet5 = 'R'; }
                if(randlet5 == '18') { randlet5 = 'S'; }
                if(randlet5 == '19') { randlet5 = 'T'; }
                if(randlet5 == '20') { randlet5 = 'U'; }
                if(randlet5 == '21') { randlet5 = 'V'; }
                if(randlet5 == '22') { randlet5 = 'W'; }
                if(randlet5 == '23') { randlet5 = 'X'; }
                if(randlet5 == '24') { randlet5 = 'Y'; }
                if(randlet5 == '25') { randlet5 = 'Z'; }
                if(randlet6 == '0') { randlet6 = 'A'; }
                if(randlet6 == '1') { randlet6 = 'B'; }
                if(randlet6 == '2') { randlet6 = 'C'; }
                if(randlet6 == '3') { randlet6 = 'D'; }
                if(randlet6 == '4') { randlet6 = 'E'; }
                if(randlet6 == '5') { randlet6 = 'F'; }
                if(randlet6 == '6') { randlet6 = 'G'; }
                if(randlet6 == '7') { randlet6 = 'H'; }
                if(randlet6 == '8') { randlet6 = 'I'; }
                if(randlet6 == '9') { randlet6 = 'J'; }
                if(randlet6 == '10') { randlet6 = 'K'; }
                if(randlet6 == '11') { randlet6 = 'L'; }
                if(randlet6 == '12') { randlet6 = 'M'; }
                if(randlet6 == '13') { randlet6 = 'N'; }
                if(randlet6 == '14') { randlet6 = 'O'; }
                if(randlet6 == '15') { randlet6 = 'P'; }
                if(randlet6 == '16') { randlet6 = 'Q'; }
                if(randlet6 == '17') { randlet6 = 'R'; }
                if(randlet6 == '18') { randlet6 = 'S'; }
                if(randlet6 == '19') { randlet6 = 'T'; }
                if(randlet6 == '20') { randlet6 = 'U'; }
                if(randlet6 == '21') { randlet6 = 'V'; }
                if(randlet6 == '22') { randlet6 = 'W'; }
                if(randlet6 == '23') { randlet6 = 'X'; }
                if(randlet6 == '24') { randlet6 = 'Y'; }
                if(randlet6 == '25') { randlet6 = 'Z'; }
                if(randlet7 == '0') { randlet7 = 'A'; }
                if(randlet7 == '1') { randlet7 = 'B'; }
                if(randlet7 == '2') { randlet7 = 'C'; }
                if(randlet7 == '3') { randlet7 = 'D'; }
                if(randlet7 == '4') { randlet7 = 'E'; }
                if(randlet7 == '5') { randlet7 = 'F'; }
                if(randlet7 == '6') { randlet7 = 'G'; }
                if(randlet7 == '7') { randlet7 = 'H'; }
                if(randlet7 == '8') { randlet7 = 'I'; }
                if(randlet7 == '9') { randlet7 = 'J'; }
                if(randlet7 == '10') { randlet7 = 'K'; }
                if(randlet7 == '11') { randlet7 = 'L'; }
                if(randlet7 == '12') { randlet7 = 'M'; }
                if(randlet7 == '13') { randlet7 = 'N'; }
                if(randlet7 == '14') { randlet7 = 'O'; }
                if(randlet7 == '15') { randlet7 = 'P'; }
                if(randlet7 == '16') { randlet7 = 'Q'; }
                if(randlet7 == '17') { randlet7 = 'R'; }
                if(randlet7 == '18') { randlet7 = 'S'; }
                if(randlet7 == '19') { randlet7 = 'T'; }
                if(randlet7 == '20') { randlet7 = 'U'; }
                if(randlet7 == '21') { randlet7 = 'V'; }
                if(randlet7 == '22') { randlet7 = 'W'; }
                if(randlet7 == '23') { randlet7 = 'X'; }
                if(randlet7 == '24') { randlet7 = 'Y'; }
                if(randlet7 == '25') { randlet7 = 'Z'; }
                if(randlet8 == '0') { randlet8 = 'A'; }
                if(randlet8 == '1') { randlet8 = 'B'; }
                if(randlet8 == '2') { randlet8 = 'C'; }
                if(randlet8 == '3') { randlet8 = 'D'; }
                if(randlet8 == '4') { randlet8 = 'E'; }
                if(randlet8 == '5') { randlet8 = 'F'; }
                if(randlet8 == '6') { randlet8 = 'G'; }
                if(randlet8 == '7') { randlet8 = 'H'; }
                if(randlet8 == '8') { randlet8 = 'I'; }
                if(randlet8 == '9') { randlet8 = 'J'; }
                if(randlet8 == '10') { randlet8 = 'K'; }
                if(randlet8 == '11') { randlet8 = 'L'; }
                if(randlet8 == '12') { randlet8 = 'M'; }
                if(randlet8 == '13') { randlet8 = 'N'; }
                if(randlet8 == '14') { randlet8 = 'O'; }
                if(randlet8 == '15') { randlet8 = 'P'; }
                if(randlet8 == '16') { randlet8 = 'Q'; }
                if(randlet8 == '17') { randlet8 = 'R'; }
                if(randlet8 == '18') { randlet8 = 'S'; }
                if(randlet8 == '19') { randlet8 = 'T'; }
                if(randlet8 == '20') { randlet8 = 'U'; }
                if(randlet8 == '21') { randlet8 = 'V'; }
                if(randlet8 == '22') { randlet8 = 'W'; }
                if(randlet8 == '23') { randlet8 = 'X'; }
                if(randlet8 == '24') { randlet8 = 'Y'; }
                if(randlet8 == '25') { randlet8 = 'Z'; }
                if(randlet9 == '0') { randlet9 = 'A'; }
                if(randlet9 == '1') { randlet9 = 'B'; }
                if(randlet9 == '2') { randlet9 = 'C'; }
                if(randlet9 == '3') { randlet9 = 'D'; }
                if(randlet9 == '4') { randlet9 = 'E'; }
                if(randlet9 == '5') { randlet9 = 'F'; }
                if(randlet9 == '6') { randlet9 = 'G'; }
                if(randlet9 == '7') { randlet9 = 'H'; }
                if(randlet9 == '8') { randlet9 = 'I'; }
                if(randlet9 == '9') { randlet9 = 'J'; }
                if(randlet9 == '10') { randlet9 = 'K'; }
                if(randlet9 == '11') { randlet9 = 'L'; }
                if(randlet9 == '12') { randlet9 = 'M'; }
                if(randlet9 == '13') { randlet9 = 'N'; }
                if(randlet9 == '14') { randlet9 = 'O'; }
                if(randlet9 == '15') { randlet9 = 'P'; }
                if(randlet9 == '16') { randlet9 = 'Q'; }
                if(randlet9 == '17') { randlet9 = 'R'; }
                if(randlet9 == '18') { randlet9 = 'S'; }
                if(randlet9 == '19') { randlet9 = 'T'; }
                if(randlet9 == '20') { randlet9 = 'U'; }
                if(randlet9 == '21') { randlet9 = 'V'; }
                if(randlet9 == '22') { randlet9 = 'W'; }
                if(randlet9 == '23') { randlet9 = 'X'; }
                if(randlet9 == '24') { randlet9 = 'Y'; }
                if(randlet9 == '25') { randlet9 = 'Z'; }
            }
            random();
            message.channel.send(`**${message.guild.member(message.author).displayName}** _tire les lettres : **${randlet}**, **${randlet2}**, **${randlet3}**, **${randlet4}**, **${randlet5}**, **${randlet6}**, **${randlet7}**, **${randlet8}**, **${randlet9}** - Bonne chance !_`);
};